backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "assets/img"

collections:
  - name: "adega"
    label: "Gerenciar Adega"
    files:
      - name: "estoque"
        label: "Todos os Vinhos"
        file: "dados/estoque.json"
        fields:
          - name: "produtos"
            label: "Lista de Produtos"
            widget: "list"
            fields:
              - {label: "ID (Ex: tin01)", name: "id", widget: "string"}
              - {label: "Nome do Vinho", name: "nome", widget: "string"}
              - {label: "Categoria", name: "categoria", widget: "select", options: ["tinto", "branco", "rose", "espumantes", "laranja", "importados", "semalcool", "cooler"]}
              - {label: "Preço (Use ponto: 109.50)", name: "preco", widget: "number", value_type: "float"}
              - {label: "Imagem da Garrafa", name: "imagem", widget: "image"}
              - {label: "Descrição Curta", name: "descricao", widget: "text"}

  - name: "blog"
    label: "Blog / Notícias"
    files:
      - name: "posts"
        label: "Todos os Posts"
        file: "dados/blog.json"
        fields:
          - name: "artigos"
            label: "Artigos"
            widget: "list"
            fields:
              - {label: "Título", name: "titulo", widget: "string"}
              - {label: "Data", name: "data", widget: "datetime"}
              - {label: "Imagem de Capa", name: "imagem", widget: "image"}
              - {label: "Resumo", name: "resumo", widget: "text"}
              - {label: "Conteúdo", name: "conteudo", widget: "markdown"}
              - {label: "Slug (URL)", name: "slug", widget: "string"}

  - name: "visuais"
    label: "Imagens das Categorias"
    files:
      - name: "banners"
        label: "Cards Informativos"
        file: "dados/categorias.json"
        fields:
          - name: "configs"
            label: "Configurar Categorias"
            widget: "list"
            fields:
              - {label: "Categoria", name: "id", widget: "select", options: ["tinto", "branco", "rose", "espumantes", "laranja", "importados", "semalcool", "cooler"]}
              - {label: "Imagens do Card (Carrossel)", name: "imagens", widget: "list", field: {label: "Imagem", name: "url", widget: "image"}}
